/* File Name : mc_prng.c
 * Purpose   : To develop a Pseudo Random Number Generator using linear congruential method
 * Process   : Initially we seed a random number generator and threads generate the random numbers 
 *             using initial input Additive Constant and multipliers  in the given period
 * Compile   : cc mc_prng.c -fopenmp
 * Execute   : ./a.out
 * Inputs    : Seed Value,Maximum Period,Random numbers required
 * Outputs   : List of random numbers
 */ 

#include<stdio.h>
#include<omp.h>

int x0;        //seed value
int a=2;         //multiplier
int c=1;         //Additive constant
int M;         //Maximum Period
int xi;        //next value
int no;        //number of random numbers 
int i;         //loop counter
int acc[100];  //Accumulator to store numbers
void calc_rand_no(int x0,int M,int n0);
void main()
{
 int my_rank;
 int num_threads;
 int my_seed;
 printf("\nEnter the Seed value : ");
 scanf("%d",&x0); 
 printf("\nEnter Maximum Period : ");
 scanf("%d",&M);
 printf("\nEnter the number of random numbers required : ");
 scanf("%d",&no); 
 #pragma omp parallel num_threads(4) private(xi)
 {
   my_rank= omp_get_thread_num();
   my_seed=x0*my_rank;
   xi=my_seed;
   #pragma omp for
   for(i=0;i<no;i++)
    {
     xi= (xi*a+c)%M;
     printf("\nRandom Number generated by thread %d is %d\n",my_rank,xi);
    } 
 }
}//end main

/* Purpose : To generate the random numbers 
 * Input   : seed value,period ans initial value
 * Output  : Random numbers 
 */
void calc_rand_no(int x0,int M,int no)
{
  int my_rank= omp_get_thread_num();
  int num_threads= omp_get_num_threads();
  int my_seed=x0*my_rank;
  printf("\nSeed Value of %d is %d\n",my_rank,my_seed);
  #pragma omp critical
  {
    for(i=1;i<no;i++)
    {
     acc[i]= (acc[i-1]*a+c)%M;
     printf("\nRandom Number generated by thread %d is %d\n",my_rank,acc[i]);
    }
  }  

  
}
